name: wosool
description: "تطبيق وُصول لإدارة نقل عمال المصانع وحساب الرحلات"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0 # تم تعديله ليتوافق مع معظم إصدارات فلاتر الحالية

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # قاعدة البيانات
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # إدارة الحالة والوقت
  provider: ^6.1.2
  intl: ^0.19.0
  
  # ملفات ومشاركة (تم تحديث الإصدارات)
  share_plus: ^10.1.0
  path_provider: ^2.1.2
  pdf: ^3.11.1
  printing: ^5.14.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  # إضافة الخطوط العربية ليعمل التقرير والتطبيق بشكل احترافي
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700